version: '3'

services:
  postgres:
    image: postgres:13
    env_file: ./.env
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    env_file: ./.env
    ports:
      - 8080:80
